# Generated by Django 3.1.7 on 2021-05-21 02:16

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_review_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='image/actor_image'),
            preserve_default=False,
        ),
    ]
