# Generated by Django 3.1.7 on 2021-05-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_actor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
