# Generated by Django 3.1.7 on 2021-05-23 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20210522_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
        migrations.AddField(
            model_name='actor',
            name='like_users',
            field=models.ManyToManyField(related_name='like_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='scrap_users',
            field=models.ManyToManyField(related_name='scrap_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
