# Generated by Django 3.1.7 on 2021-05-25 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210523_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
