# Generated by Django 3.1.7 on 2021-05-25 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_auto_20210525_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='like_users',
            field=models.ManyToManyField(related_name='like_actors', to=settings.AUTH_USER_MODEL),
        ),
    ]
