# Generated by Django 3.1.7 on 2021-05-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sns_id',
            field=models.CharField(max_length=100),
        ),
    ]
